type Ecode = {
  ecode: string;
  name: string;
  status: 'halal' | 'haram' | 'mushbooh';
};

export const ECODES: Ecode[] = [
  { ecode: 'E100', name: 'Curcumin/Turmeric', status: 'mushbooh' },
  { ecode: 'E101', name: 'Riboflavin (Vitamin B2)', status: 'mushbooh' },
  { ecode: 'E102', name: 'Tartazine', status: 'halal' },
  { ecode: 'E103', name: 'Chrysoine Resocinol', status: 'mushbooh' },
  { ecode: 'E104', name: 'Quinoline Yellow', status: 'mushbooh' },
  { ecode: 'E105', name: 'Fast Yellow AB', status: 'mushbooh' },
  { ecode: 'E107', name: 'Yellow 2G', status: 'halal' },
  {
    ecode: 'E110',
    name: 'Sunset Yellow FCF / Orange Yellow S',
    status: 'mushbooh',
  },
  { ecode: 'E120', name: 'Cochineal / Carminic Acid', status: 'haram' },
  { ecode: 'E122', name: 'Carmoisine / Azorubine', status: 'mushbooh' },
  { ecode: 'E123', name: 'Amaranth Dye', status: 'mushbooh' },
  { ecode: 'E124', name: 'Ponceau 4R / Cochineal Red A', status: 'haram' },
  { ecode: 'E127', name: 'Erythrosine BS', status: 'mushbooh' },
  { ecode: 'E128', name: 'Red 2G', status: 'mushbooh' },
  { ecode: 'E129', name: 'Allura Red AC', status: 'halal' },
  { ecode: 'E131', name: 'Patent Blue V', status: 'mushbooh' },
  { ecode: 'E132', name: 'Indigo Carmine / Idigotine', status: 'mushbooh' },
  { ecode: 'E133', name: 'Brilliant Blue FCF', status: 'halal' },
  { ecode: 'E140', name: 'Chlorophyll', status: 'mushbooh' },
  { ecode: 'E150a', name: 'Caramel Color/with chemicals', status: 'halal' },
  { ecode: 'E150b', name: 'Caramel Color/with chemicals', status: 'halal' },
  { ecode: 'E150c', name: 'Caramel Color/with chemicals', status: 'halal' },
  { ecode: 'E150d', name: 'Caramel Color/with chemicals', status: 'halal' },
  { ecode: 'E151', name: 'Black PN / Brilliant Black BN', status: 'halal' },
  {
    ecode: 'E153',
    name: 'Carbon Black / Vegetable Carbon (Charcoal)',
    status: 'mushbooh',
  },
  { ecode: 'E154', name: 'Brown FK', status: 'halal' },
  { ecode: 'E155', name: 'Brown HT', status: 'mushbooh' },
  { ecode: 'E160a', name: 'Alpha, Beta, Gamma Carotene', status: 'mushbooh' },
  { ecode: 'E160b', name: 'Annatto, Bixin, Norbixin', status: 'halal' },
  { ecode: 'E160c', name: 'Capsanthin / Capsorbin', status: 'halal' },
  { ecode: 'E160d', name: 'Lycopene', status: 'mushbooh' },
  { ecode: 'E160e', name: 'Beta-apo-8-carotenal', status: 'mushbooh' },
  {
    ecode: 'E160f',
    name: 'Ethyl ester of Beta-apo-8-cartonoic acid',
    status: 'mushbooh',
  },
  { ecode: 'E161a', name: 'Flavoxanthin', status: 'mushbooh' },
  { ecode: 'E161b', name: 'Lutein', status: 'mushbooh' },
  { ecode: 'E161c', name: 'Cryptoxanthin', status: 'mushbooh' },
  { ecode: 'E161d', name: 'Rubixanthin', status: 'mushbooh' },
  { ecode: 'E161e', name: 'Violaxanthin', status: 'mushbooh' },
  { ecode: 'E161f', name: 'Rhodoxanthin', status: 'mushbooh' },
  { ecode: 'E161g', name: 'Canthaxanthin', status: 'mushbooh' },
  { ecode: 'E162', name: 'Beetroot Red / Betanin', status: 'mushbooh' },
  { ecode: 'E163', name: 'Anthocyanins', status: 'halal' },
  { ecode: 'E170', name: 'Calcium Carbonate (Chalk)', status: 'halal' },
  { ecode: 'E171', name: 'Titanium Dioxide', status: 'halal' },
  { ecode: 'E172', name: 'Iron Oxides and Iron Hydroxides', status: 'halal' },
  { ecode: 'E173', name: 'Aluminium', status: 'halal' },
  { ecode: 'E174', name: 'Silver', status: 'halal' },
  { ecode: 'E175', name: 'Gold', status: 'halal' },
  {
    ecode: 'E180',
    name: 'Pigment Rubine / Lithol Rubine BK',
    status: 'mushbooh',
  },
  { ecode: 'E200', name: 'Sorbic Acid', status: 'halal' },
  { ecode: 'E201', name: 'Soduim Sorbate', status: 'halal' },
  { ecode: 'E202', name: 'Potassium Sorbate', status: 'halal' },
  { ecode: 'E203', name: 'Calcium Sorbate', status: 'halal' },
  { ecode: 'E203', name: 'Calcium Sorbate', status: 'halal' },
  { ecode: 'E210', name: 'Benzoic Acid', status: 'mushbooh' },
  { ecode: 'E211', name: 'Sodium Benzoate', status: 'halal' },
  { ecode: 'E212', name: 'Potassium Benzoate', status: 'halal' },
  { ecode: 'E213', name: 'Calcium Benzoate', status: 'mushbooh' },
  { ecode: 'E214', name: 'Ethyl 4-hydroxybenzoate', status: 'mushbooh' },
  {
    ecode: 'E215',
    name: 'Ethyl 4-hydroxybenzoate, Sodium Salt',
    status: 'halal',
  },
  { ecode: 'E216', name: 'Propyl 4-hydroxybenzoate', status: 'mushbooh' },
  {
    ecode: 'E217',
    name: 'Propyl 4-hydroxybenzoate, Sodium Salt',
    status: 'halal',
  },
  { ecode: 'E218', name: 'Methyl 4-hydroxybenzoate', status: 'halal' },
  {
    ecode: 'E219',
    name: 'Methyl 4-hydroxybenzoate, Sodium Salt',
    status: 'halal',
  },
  { ecode: 'E220', name: 'Sulphur Dioxide', status: 'halal' },
  { ecode: 'E221', name: 'Sodium Sulphite', status: 'halal' },
  { ecode: 'E222', name: 'Sodium Hydrogen Sulphite', status: 'halal' },
  { ecode: 'E223', name: 'Sodium Metabisulphite', status: 'halal' },
  { ecode: 'E224', name: 'Potassium Metabisulphite', status: 'halal' },
  { ecode: 'E226', name: 'Calcium Sulphite', status: 'halal' },
  { ecode: 'E227', name: 'Calcium Hydrogen Sulphite', status: 'halal' },
  { ecode: 'E228', name: 'Potassium Hydrogen sulphite', status: 'halal' },
  { ecode: 'E230', name: 'Biphenyl / Diphenyl', status: 'halal' },
  { ecode: 'E231', name: '2-Hydroxybiphenyl', status: 'halal' },
  { ecode: 'E232', name: 'Sodium Biphenyl-2-yl Oxide', status: 'halal' },
  { ecode: 'E233', name: '2-(Thiazol-4-yl) Benzimidazole', status: 'halal' },
  { ecode: 'E234', name: 'Nisin', status: 'mushbooh' },
  { ecode: 'E235', name: 'Natamycin', status: 'halal' },
  { ecode: 'E239', name: 'Hexamine', status: 'halal' },
  { ecode: 'E242', name: 'Dimethyl dicarbonate', status: 'halal' },
  { ecode: 'E249', name: 'Potassium Nitrate', status: 'halal' },
  { ecode: 'E250', name: 'Sodium Nitrite', status: 'halal' },
  { ecode: 'E251', name: 'Sodium Nitrate', status: 'halal' },
  { ecode: 'E252', name: 'Potassium Nitrate(Saltpetre)', status: 'mushbooh' },
  { ecode: 'E260', name: 'Acetic Acid', status: 'halal' },
  { ecode: 'E261', name: 'Potassium Acetate', status: 'halal' },
  { ecode: 'E262', name: 'Sodium Acetates', status: 'halal' },
  { ecode: 'E263', name: 'Calcium Acetate', status: 'halal' },
  { ecode: 'E270', name: 'Lactic Acid', status: 'mushbooh' },
  { ecode: 'E280', name: 'Propionic Acid', status: 'mushbooh' },
  { ecode: 'E281', name: 'Sodium Propionate', status: 'halal' },
  { ecode: 'E282', name: 'Calcium Propionate', status: 'halal' },
  { ecode: 'E283', name: 'Potassium Propionate', status: 'halal' },
  { ecode: 'E284', name: 'Boric acid', status: 'halal' },
  { ecode: 'E285', name: 'Sodium tetraborate; Borax', status: 'halal' },
  { ecode: 'E290', name: 'Carbon Dioxide', status: 'halal' },
  { ecode: 'E296', name: 'Malic Acid', status: 'halal' },
  { ecode: 'E297', name: 'Fumaric Acid', status: 'halal' },
  { ecode: 'E300', name: 'L-Ascorbic Acid (Vitamin C)', status: 'halal' },
  { ecode: 'E301', name: 'Sodium-L-Ascorbate', status: 'halal' },
  { ecode: 'E302', name: 'Calcium-L-Ascorbate', status: 'halal' },
  { ecode: 'E304', name: 'Ascorbyl Palmitate', status: 'mushbooh' },
  { ecode: 'E306', name: 'Antioxidants- Vitamin E', status: 'mushbooh' },
  { ecode: 'E307', name: 'Synthetic Alpha-Tocopherol', status: 'halal' },
  { ecode: 'E308', name: 'Synthetic Gamma-Tocopherol', status: 'halal' },
  { ecode: 'E309', name: 'Synthetic Delta-Tocopherol', status: 'halal' },
  { ecode: 'E310', name: 'Propyl Gallate', status: 'halal' },
  { ecode: 'E311', name: 'Octyl Gallate', status: 'halal' },
  { ecode: 'E312', name: 'Dodecyl Gallate', status: 'halal' },
  { ecode: 'E315', name: 'Erythorbic acid', status: 'halal' },
  { ecode: 'E316', name: 'Sodium erythorbate', status: 'halal' },
  { ecode: 'E316', name: 'Sodium erythorbate', status: 'halal' },
  { ecode: 'E316', name: 'Sodium erythorbate', status: 'halal' },
  { ecode: 'E319', name: 'Tert-Butylhydroquinone (TBHQ)', status: 'mushbooh' },
  { ecode: 'E320', name: 'Butylated Hydroxyanisole (BHA)', status: 'mushbooh' },
  { ecode: 'E321', name: 'Butylated Hydroxytoluene (BHT)', status: 'mushbooh' },
  { ecode: 'E322', name: 'Lecithin', status: 'halal' },
  { ecode: 'E325', name: 'Sodium Lactate', status: 'mushbooh' },
  { ecode: 'E326', name: 'Potassium Lactate', status: 'mushbooh' },
  { ecode: 'E327', name: 'Calcium Lactate', status: 'mushbooh' },
  { ecode: 'E330', name: 'Citric Acid', status: 'halal' },
  { ecode: 'E331', name: 'Sodium Citrates', status: 'halal' },
  { ecode: 'E332', name: 'Potassium Citrates', status: 'halal' },
  { ecode: 'E333', name: 'Calcium Citrates', status: 'halal' },
  { ecode: 'E334', name: 'Tartaric Acid', status: 'mushbooh' },
  { ecode: 'E335', name: 'Sodium Tartrates', status: 'mushbooh' },
  {
    ecode: 'E336',
    name: 'Potassium Tartrates (Cream of Tartar)',
    status: 'mushbooh',
  },
  { ecode: 'E337', name: 'Potassium Sodium Tartrates', status: 'mushbooh' },
  { ecode: 'E338', name: 'Orthophosphoric Acid', status: 'halal' },
  { ecode: 'E339', name: 'Sodium Phosphates', status: 'mushbooh' },
  { ecode: 'E340', name: 'Potassium Phosphates', status: 'mushbooh' },
  { ecode: 'E341', name: 'Calcium Phosphates', status: 'mushbooh' },
  { ecode: 'E343', name: 'Magnesium phosphate', status: 'mushbooh' },
  { ecode: 'E350', name: 'Sodium Malate', status: 'halal' },
  { ecode: 'E351', name: 'Potassium Malate', status: 'halal' },
  { ecode: 'E352', name: 'Calcium Malate', status: 'halal' },
  { ecode: 'E353', name: 'Metataric Acid', status: 'halal' },
  { ecode: 'E354', name: 'Calcium Tartrate', status: 'haram' },
  { ecode: 'E355', name: 'Adipic Acid', status: 'halal' },
  { ecode: 'E356', name: 'Sodium adipate', status: 'mushbooh' },
  { ecode: 'E357', name: 'Potassium adipate', status: 'mushbooh' },
  { ecode: 'E363', name: 'Succinic Acid', status: 'halal' },
  { ecode: 'E370', name: '1,4-Heptonolactane', status: 'halal' },
  { ecode: 'E375', name: 'Nicotinic Acid', status: 'halal' },
  { ecode: 'E380', name: 'Triammonium Citrate', status: 'halal' },
  { ecode: 'E381', name: 'Ammonium Ferric Citrate', status: 'halal' },
  { ecode: 'E385', name: 'Calcium Disodium EDTA', status: 'halal' },
  { ecode: 'E400', name: 'Alginic Acid', status: 'halal' },
  { ecode: 'E401', name: 'Sodium Alginate', status: 'halal' },
  { ecode: 'E402', name: 'Potassium Alginate', status: 'halal' },
  { ecode: 'E403', name: 'Ammonium Alginate', status: 'halal' },
  { ecode: 'E404', name: 'Calcium Alginate', status: 'halal' },
  { ecode: 'E405', name: 'Propane-1,2-Diol Alginate', status: 'halal' },
  { ecode: 'E406', name: 'Agar', status: 'halal' },
  { ecode: 'E407', name: 'Carrageenan', status: 'mushbooh' },
  { ecode: 'E410', name: 'Locust Bean Gum (Carob Gum)', status: 'halal' },
  { ecode: 'E412', name: 'Guar Gum', status: 'halal' },
  { ecode: 'E413', name: 'Tragacanth', status: 'halal' },
  { ecode: 'E414', name: 'Gum Acacia (Gum Arabic)', status: 'halal' },
  { ecode: 'E415', name: 'Xanthan Gum', status: 'halal' },
  { ecode: 'E416', name: 'Karaya Gum', status: 'halal' },
  { ecode: 'E417', name: 'Tara Gum', status: 'halal' },
  { ecode: 'E418', name: 'Gellan Gum', status: 'halal' },
  { ecode: 'E420', name: 'Sorbitol', status: 'halal' },
  { ecode: 'E421', name: 'Mannitol', status: 'halal' },
  { ecode: 'E422', name: 'Glycerol', status: 'mushbooh' },
  { ecode: 'E425', name: 'Konjac', status: 'halal' },
  { ecode: 'E430', name: 'Polyoxyethane (8) Stearate', status: 'mushbooh' },
  { ecode: 'E431', name: 'Polyoxyethane (40) Stearate', status: 'mushbooh' },
  {
    ecode: 'E432',
    name: 'Polyoxyethane (20) Sorbitan / Polysorbate 20',
    status: 'mushbooh',
  },
  {
    ecode: 'E433',
    name: 'Polyoxyethane (20) Sorbitan Mono-oleate / Polysorbate 80.',
    status: 'mushbooh',
  },
  {
    ecode: 'E434',
    name: 'Polyoxyethane (20) Sorbitan Monopalmitate / Polysorbate 40',
    status: 'mushbooh',
  },
  {
    ecode: 'E435',
    name: 'Polyoxyethane (20) Sorbitan Monostearate / Polysorbate 60',
    status: 'mushbooh',
  },
  {
    ecode: 'E436',
    name: 'Polyoxyethane (20) Sorbitan Tristearate / Polysorbate 65',
    status: 'mushbooh',
  },
  { ecode: 'E440a', name: 'Pectin', status: 'mushbooh' },
  { ecode: 'E440b', name: 'Amidated Pectin', status: 'mushbooh' },
  { ecode: 'E441', name: 'Gelatin', status: 'mushbooh' },
  { ecode: 'E442', name: 'Ammonium phosphatides', status: 'mushbooh' },
  { ecode: 'E444', name: 'Sucrose accetate isobutyrate', status: 'halal' },
  { ecode: 'E445', name: 'Glycerol esters of wood rosin', status: 'halal' },
  {
    ecode: 'E450a',
    name: 'Sodium and Potassium Phosphates and Polyphosphates',
    status: 'mushbooh',
  },
  {
    ecode: 'E450b',
    name: 'Sodium and Potassium Phosphates and Polyphosphates',
    status: 'mushbooh',
  },
  {
    ecode: 'E450c',
    name: 'Sodium and Potassium Phosphates and Polyphosphates',
    status: 'mushbooh',
  },
  { ecode: 'E451', name: 'Triphosphates', status: 'mushbooh' },
  { ecode: 'E452', name: 'Polyphosphate', status: 'mushbooh' },
  { ecode: 'E459', name: 'Beta-Cyclodextrin', status: 'halal' },
  {
    ecode: 'E460',
    name: 'Microcrystalline / Powdered Cellulose',
    status: 'halal',
  },
  { ecode: 'E461', name: 'Methylcellulose', status: 'halal' },
  { ecode: 'E463', name: 'Hydroxypropylcellulose', status: 'halal' },
  { ecode: 'E464', name: 'Hydroxypropyl-Methylcellulose', status: 'halal' },
  { ecode: 'E465', name: 'Ethylmethylcellulose', status: 'halal' },
  {
    ecode: 'E466',
    name: 'Carboxymethylcellulose, Sodium Salt',
    status: 'halal',
  },
  { ecode: 'E467', name: 'Sodium Carboxy methyl cellulose', status: 'halal' },
  {
    ecode: 'E468',
    name: 'Cross Linked Carboxy methyl cellulose',
    status: 'halal',
  },
  {
    ecode: 'E469',
    name: 'Enzymatically hydrolyzed Carboxy Methyl Cellulose',
    status: 'halal',
  },
  {
    ecode: 'E470',
    name: 'Sodium, Potassium and Calcium Salts of Fatty Acids',
    status: 'mushbooh',
  },
  {
    ecode: 'E471',
    name: 'Mono-and Diglycerides of Fatty Acids',
    status: 'mushbooh',
  },
  {
    ecode: 'E472',
    name: 'Various Esters of Mono-and Diglycerides of Fatty Acids',
    status: 'mushbooh',
  },
  {
    ecode: 'E472e',
    name: 'Monoand diacetyl tartaric acid esters of mono & diglycerides',
    status: 'mushbooh',
  },
  { ecode: 'E473', name: 'Sucrose Esters of Fatty Acids', status: 'mushbooh' },
  { ecode: 'E474', name: 'Sucroglycerides', status: 'mushbooh' },
  {
    ecode: 'E475',
    name: 'Polyglycerol Esters of Fatty Acids',
    status: 'mushbooh',
  },
  {
    ecode: 'E476',
    name: 'Polyglycerol Esters of Polycondensed Esters of Caster Oil',
    status: 'mushbooh',
  },
  {
    ecode: 'E477',
    name: 'Propane-1,2-Diol Esters of Fatty Acids',
    status: 'mushbooh',
  },
  {
    ecode: 'E478',
    name: 'Lactylated Fatty Acid Esters of Glycerol and Propane-1,2-Diol',
    status: 'mushbooh',
  },
  {
    ecode: 'E479b',
    name: 'Thermally oxidized soybean oil interacted with mono and diglycerides of fatty acids',
    status: 'mushbooh',
  },
  { ecode: 'E481', name: 'Sodium Stearoyl-2-Lactylate', status: 'mushbooh' },
  { ecode: 'E482', name: 'Calcium Stearoyl-2-Lactylate', status: 'mushbooh' },
  { ecode: 'E483', name: 'Stearyl Tartrate', status: 'mushbooh' },
  { ecode: 'E491', name: 'Sorbitan Monostearate', status: 'mushbooh' },
  { ecode: 'E492', name: 'Sorbitan Tristearate', status: 'mushbooh' },
  { ecode: 'E493', name: 'Sorbitan Monolaurate', status: 'mushbooh' },
  { ecode: 'E494', name: 'Sorbitan Mono-oleate', status: 'mushbooh' },
  { ecode: 'E495', name: 'Sorbitan Monopalmitate', status: 'mushbooh' },
  { ecode: 'E496', name: 'Sorbitan Trioleate', status: 'mushbooh' },
  {
    ecode: 'E500',
    name: 'Sodium Carbonate / Sodium Bicarbonate',
    status: 'halal',
  },
  {
    ecode: 'E501',
    name: 'Potassium Carbonate / Potassium Bicarbonate',
    status: 'halal',
  },
  { ecode: 'E503', name: 'Ammonium Carbonate', status: 'halal' },
  { ecode: 'E504', name: 'Magnesium Carbonate', status: 'halal' },
  { ecode: 'E507', name: 'Hydrochloric Acid', status: 'halal' },
  { ecode: 'E508', name: 'Potassium Chloride', status: 'halal' },
  { ecode: 'E509', name: 'Calcium Chloride', status: 'halal' },
  { ecode: 'E510', name: 'Ammonium Chloride', status: 'halal' },
  { ecode: 'E511', name: 'Magnesium Chloride', status: 'halal' },
  { ecode: 'E512', name: 'Stannous chloride', status: 'halal' },
  { ecode: 'E513', name: 'Sulphuric Acid', status: 'halal' },
  { ecode: 'E514', name: 'Sodium Sulphate', status: 'halal' },
  { ecode: 'E515', name: 'Potassium Sulphate', status: 'halal' },
  { ecode: 'E516', name: 'Calcium Sulphate', status: 'halal' },
  { ecode: 'E517', name: 'Ammonium Sulphate', status: 'halal' },
  { ecode: 'E518', name: 'Magnesium Sulphate', status: 'halal' },
  { ecode: 'E520', name: 'Almunium sulphate', status: 'halal' },
  { ecode: 'E521', name: 'Alimunium Sodium Sulphate', status: 'halal' },
  { ecode: 'E522', name: 'Aluminium Potassium Sulphate', status: 'halal' },
  { ecode: 'E523', name: 'Aluminium Ammonium Sulphate', status: 'halal' },
  { ecode: 'E524', name: 'Sodium Hydroxide', status: 'halal' },
  { ecode: 'E525', name: 'Potassium Hydroxide', status: 'halal' },
  { ecode: 'E526', name: 'Calcium Hydroxide', status: 'halal' },
  { ecode: 'E527', name: 'Ammonium Hydroxide', status: 'halal' },
  { ecode: 'E528', name: 'Magnesium Hydroxide', status: 'halal' },
  { ecode: 'E529', name: 'Calcium Oxide', status: 'halal' },
  { ecode: 'E530', name: 'Magnesium Oxide', status: 'halal' },
  { ecode: 'E535', name: 'Sodium Ferrocyanide', status: 'halal' },
  { ecode: 'E536', name: 'Potassium Ferrocyanide', status: 'halal' },
  { ecode: 'E538', name: 'Calcium Ferrocyanide', status: 'halal' },
  { ecode: 'E540', name: 'Dicalcium Ferrocyanide', status: 'halal' },
  { ecode: 'E541', name: 'Sodium Aluminium Phosphate', status: 'halal' },
  {
    ecode: 'E542',
    name: 'Edible Bone Phosphate (Bone-Meal)',
    status: 'mushbooh',
  },
  { ecode: 'E544', name: 'Calcium Polyphosphates', status: 'mushbooh' },
  { ecode: 'E545', name: 'Ammonium Polyphosphates', status: 'mushbooh' },
  { ecode: 'E550', name: 'Sodium Silicate', status: 'halal' },
  { ecode: 'E551', name: 'Silicon Dioxide (Silica Salt)', status: 'halal' },
  { ecode: 'E552', name: 'Calcium Silicate', status: 'halal' },
  {
    ecode: 'E553',
    name: 'Magnesium Silicate / Magnesium Trisilicate (Talc)',
    status: 'halal',
  },
  { ecode: 'E554', name: 'Aluminium Sodium Silicate', status: 'halal' },
  { ecode: 'E555', name: 'Potassium Aluminium Sillicate', status: 'halal' },
  { ecode: 'E556', name: 'Aluminium Calcium Silicate', status: 'halal' },
  { ecode: 'E558', name: 'Bentonite', status: 'halal' },
  { ecode: 'E559', name: 'Kaolin (Aluminium Silicate)', status: 'halal' },
  { ecode: 'E570', name: 'Stearic Acid', status: 'mushbooh' },
  { ecode: 'E572', name: 'Magnesium Stearate', status: 'mushbooh' },
  { ecode: 'E574', name: 'Gluconic Acids', status: 'halal' },
  { ecode: 'E575', name: 'Glucono Delta-Lactone', status: 'halal' },
  { ecode: 'E576', name: 'Sodium Gluconate', status: 'halal' },
  { ecode: 'E577', name: 'Potassium Gluconate', status: 'halal' },
  { ecode: 'E578', name: 'Calcium Gluconate', status: 'halal' },
  { ecode: 'E585', name: 'Ferrous Lactate', status: 'halal' },
  { ecode: 'E620', name: 'L-Glutamic Acid', status: 'mushbooh' },
  { ecode: 'E621', name: 'Monosodium Glutamate (MSG)', status: 'mushbooh' },
  { ecode: 'E622', name: 'Monopotassium Glutamate', status: 'mushbooh' },
  { ecode: 'E623', name: 'Calcium Glutamate', status: 'mushbooh' },
  { ecode: 'E624', name: 'Mono ammonium glutamate', status: 'mushbooh' },
  { ecode: 'E625', name: 'Magnesium diglutamate', status: 'mushbooh' },
  { ecode: 'E626', name: 'Guanylic Acid', status: 'mushbooh' },
  { ecode: 'E627', name: 'Sodium Guanylate', status: 'mushbooh' },
  { ecode: 'E628', name: 'Dipotassium Guanylate', status: 'mushbooh' },
  { ecode: 'E629', name: 'Calcium Guanylate', status: 'mushbooh' },
  { ecode: 'E630', name: 'Inosinic acid', status: 'mushbooh' },
  { ecode: 'E631', name: 'Sodium Inosinate', status: 'mushbooh' },
  { ecode: 'E632', name: 'Dipotassium Inosinate', status: 'mushbooh' },
  { ecode: 'E633', name: 'Calcium Inosinate', status: 'mushbooh' },
  { ecode: 'E634', name: 'Calcium5-Ribonucleotide', status: 'mushbooh' },
  { ecode: 'E635', name: 'Sodium5-Ribonucleotide', status: 'mushbooh' },
  { ecode: 'E636', name: 'Maltol', status: 'halal' },
  { ecode: 'E637', name: 'Ethyl Maltol', status: 'halal' },
  { ecode: 'E640', name: 'Glycine and its sodium salt', status: 'mushbooh' },
  { ecode: 'E650', name: 'Zinc Acetate', status: 'halal' },
  { ecode: 'E900', name: 'Dimethylpolysiloxane', status: 'halal' },
  { ecode: 'E901', name: 'Beeswax', status: 'halal' },
  { ecode: 'E902', name: 'Candelilla Wax', status: 'halal' },
  { ecode: 'E903', name: 'Carnauba Wax', status: 'halal' },
  { ecode: 'E904', name: 'Shellac', status: 'mushbooh' },
  { ecode: 'E905', name: 'Mineral Hydrocarbons', status: 'halal' },
  { ecode: 'E907', name: 'Refined Microcrystalline Wax', status: 'mushbooh' },
  { ecode: 'E912', name: 'Montan Acid Esters', status: 'mushbooh' },
  { ecode: 'E913', name: 'Lanolin', status: 'halal' },
  { ecode: 'E914', name: 'Oxidised Polyethylene Wax', status: 'halal' },
  { ecode: 'E920', name: 'L-Cysteine Hydrochloride', status: 'mushbooh' },
  { ecode: 'E924', name: 'Potassium Bromate', status: 'halal' },
  { ecode: 'E925', name: 'Chlorine', status: 'halal' },
  { ecode: 'E926', name: 'Chlorine Dioxide', status: 'halal' },
  { ecode: 'E927b', name: 'Carbamide', status: 'halal' },
  { ecode: 'E938', name: 'Argon', status: 'halal' },
  { ecode: 'E939', name: 'Helium', status: 'halal' },
  { ecode: 'E941', name: 'Nitrogen', status: 'halal' },
  { ecode: 'E942', name: 'Nitrous Oxide', status: 'halal' },
  { ecode: 'E943a', name: 'Butane', status: 'halal' },
  { ecode: 'E943b', name: 'Iso-butane', status: 'halal' },
  { ecode: 'E944', name: 'Propane', status: 'halal' },
  { ecode: 'E949', name: 'Hydrogen', status: 'halal' },
  { ecode: 'E951', name: 'Aspartane', status: 'haram' },
  { ecode: 'E953', name: 'Isomalt', status: 'halal' },
  { ecode: 'E954', name: 'Sacharin', status: 'halal' },
  { ecode: 'E965', name: 'Maltitol', status: 'halal' },
  { ecode: 'E966', name: 'Lactitol', status: 'mushbooh' },
  { ecode: 'E967', name: 'Xylitol', status: 'halal' },
  { ecode: 'E968', name: 'Erythritol', status: 'halal' },
  { ecode: 'E999', name: 'Quillaia Extract', status: 'haram' },
  { ecode: '1100', name: 'Amylase Enzyme', status: 'halal' },
  { ecode: '1101', name: 'Protease Enzyme', status: 'mushbooh' },
  { ecode: 'E1103', name: 'Invertase Enzyme', status: 'halal' },
  { ecode: 'E1105', name: 'Lysozyme Enzyme', status: 'halal' },
  { ecode: 'E1200', name: 'Polydextrose', status: 'halal' },
  { ecode: 'E1201', name: 'Polyvinylpyrrolidone', status: 'halal' },
  { ecode: 'E1400', name: 'Dextrin', status: 'halal' },
  { ecode: 'E1401', name: 'Acid Treated Starch', status: 'halal' },
  { ecode: 'E1404', name: 'Oxidized Starch', status: 'halal' },
  { ecode: 'E141', name: 'Copper Complex of Chlorophyll', status: 'mushbooh' },
  { ecode: 'E1410', name: 'Mono starch Phosphate', status: 'mushbooh' },
  { ecode: 'E1412', name: 'Distarch phosphate', status: 'mushbooh' },
  { ecode: 'E1413', name: 'Phosphated sistarch phosphate', status: 'mushbooh' },
  { ecode: 'E142', name: 'Green S / Acid Brilliant Green BS', status: 'halal' },
  { ecode: 'E1420', name: 'Acetylated Starch', status: 'halal' },
  { ecode: 'E1422', name: 'Acetylated distarch phosphate', status: 'mushbooh' },
  {
    ecode: 'E1442',
    name: 'Hydroxy propyl distarch phosphate',
    status: 'mushbooh',
  },
  { ecode: 'E1450', name: 'Starch Sodium Octenyl Succinate', status: 'halal' },
  { ecode: 'E1451', name: 'Acetylated Oxidized Starch', status: 'halal' },
  { ecode: 'E1505', name: 'Trietyhl Citrate', status: 'halal' },
  { ecode: 'E1518', name: 'Glyceryl Triacetate, Triacetin', status: 'halal' },
  { ecode: 'E1520', name: 'Propylene Glycol', status: 'halal' },
];
